apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-k8ts-config
  namespace: mini-k8ts
data:
  STORE_BACKEND: "postgres"
  HTTP_ADDR: ":8080"
  HEARTBEAT_INTERVAL: "5s"
  HEARTBEAT_TIMEOUT: "15s"
  SCHEDULER_TICK_INTERVAL: "2s"
  TASK_EXECUTION_TIMEOUT: "5m"
  WORKER_TOTAL_CPU: "4"
  WORKER_TOTAL_MEMORY: "8192"
  POSTGRES_DSN: "postgres://mini_k8ts:mini_k8ts@postgres:5432/mini_k8ts?sslmode=disable"
  SCHEDULER_API_BASE_URL: "http://scheduler:8080"
