apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
  namespace: mini-k8ts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: mini-k8ts:latest
          command: ["/app/worker"]
          envFrom:
            - configMapRef:
                name: mini-k8ts-config
          env:
            - name: WORKER_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
